### ISSUE TITLE
The variable SELF is unbound.

### ISSUE THREAD

**Issue by the-man-with-a-golden-mind** [naveensundarg/Common-Lisp-Actors#11]
Hi. I am trying to load that code into my repl:
```
(ql:quickload  :cl-actors)
(use-package :cl-actors)
                                        ;create the actor template
(defactor print-actor () (val) (print val) next)
                                        ; initialize a new instance
(setf printerr (print-actor))
                                        ;send values for printing
(send printerr "hello, world")
                                        ;create the template

                                        ;create the template
(defactor fact ((temp 1)) (n cust)
  (if (equal 1 n)
      (progn (send cust (* temp 1))
             (setf temp 1) next)
    (progn (setf temp (* n temp))
           (send self (- n 1) cust) next)))
                                        ;create a new instance
(setf f (fact))
                                        ; send a value
(send f 4 printerr)
```
I am using SBCL in version SBCL 1.5.7

**Comment by kenoss** [comment]
I guess this repo is a toy library.

Your code, and other examples in README.md do not work because of https://github.com/naveensundarg/Common-Lisp-Actors/blob/master/actors.lisp#L91 .  `defactor` introduces symbol `self` in cl-actors package.  This is not good way in common lisp, I think.

Replacing `(use-package :cl-actors)` in your code with `(in-package :cl-actors)` makes it work in my environment. (SBCL 1.5.7)  But it is useless in practice.

**Comment by naveensundarg** [comment]
@the-man-with-a-golden-mind there is a simple fix. Replace `self` with `cl-actors::self`. 

I will fix the code and push a new version to QuickLisp that will make your original code with just `self` work. I just need to export `self` from the `cl-actors` package. 

Please don't use @kenoss `(in-package :cl-actors)`
